"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import sudo.v1.tx_pb2

class MsgStub:
    """Msg defines the x/sudo module's Msg service. Protobuf `Msg` services are 
    called from `BaseApp` instances during `DeliverTx`. The `Msg` service will be 
    responsible for processing `sdk.Msg` requests.
    """

    def __init__(self, channel: grpc.Channel) -> None: ...
    EditSudoers: grpc.UnaryUnaryMultiCallable[
        sudo.v1.tx_pb2.MsgEditSudoers,
        sudo.v1.tx_pb2.MsgEditSudoersResponse,
    ]
    """EditSudoers updates the "Sudoers" state"""

class MsgServicer(metaclass=abc.ABCMeta):
    """Msg defines the x/sudo module's Msg service. Protobuf `Msg` services are 
    called from `BaseApp` instances during `DeliverTx`. The `Msg` service will be 
    responsible for processing `sdk.Msg` requests.
    """

    @abc.abstractmethod
    def EditSudoers(
        self,
        request: sudo.v1.tx_pb2.MsgEditSudoers,
        context: grpc.ServicerContext,
    ) -> sudo.v1.tx_pb2.MsgEditSudoersResponse:
        """EditSudoers updates the "Sudoers" state"""

def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
