# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sudo/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sudo/v1/tx.proto\x12\x0enibiru.sudo.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\"C\n\x0eMsgEditSudoers\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x11\n\tcontracts\x18\x02 \x03(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\"\x18\n\x16MsgEditSudoersResponse2\x7f\n\x03Msg\x12x\n\x0b\x45\x64itSudoers\x12\x1e.nibiru.sudo.v1.MsgEditSudoers\x1a&.nibiru.sudo.v1.MsgEditSudoersResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/nibiru/sudo/edit_sudoersB)Z\'github.com/NibiruChain/nibiru/x/sudo/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sudo.v1.tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/NibiruChain/nibiru/x/sudo/pb'
  _MSG.methods_by_name['EditSudoers']._options = None
  _MSG.methods_by_name['EditSudoers']._serialized_options = b'\202\323\344\223\002\033\"\031/nibiru/sudo/edit_sudoers'
  _MSGEDITSUDOERS._serialized_start=88
  _MSGEDITSUDOERS._serialized_end=155
  _MSGEDITSUDOERSRESPONSE._serialized_start=157
  _MSGEDITSUDOERSRESPONSE._serialized_end=181
  _MSG._serialized_start=183
  _MSG._serialized_end=310
# @@protoc_insertion_point(module_scope)
