# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/base/node/v1beta1/query.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class ConfigRequest(betterproto.Message):
    """
    ConfigRequest defines the request structure for the Config gRPC query.
    """

    pass


@dataclass
class ConfigResponse(betterproto.Message):
    """
    ConfigResponse defines the response structure for the Config gRPC query.
    """

    minimum_gas_price: str = betterproto.string_field(1)


class ServiceStub(betterproto.ServiceStub):
    """Service defines the gRPC querier service for node related queries."""

    async def config(self) -> ConfigResponse:
        """Config queries for the operator configuration."""

        request = ConfigRequest()

        return await self._unary_unary(
            "/cosmos.base.node.v1beta1.Service/Config",
            request,
            ConfigResponse,
        )
