# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epochs/event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65pochs/event.proto\x12\x10nibiru.epochs.v1\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x0f\x45ventEpochStart\x12\x14\n\x0c\x65poch_number\x18\x01 \x01(\x04\x12>\n\x10\x65poch_start_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\x90\xdf\x1f\x01\xc8\xde\x1f\x00\"%\n\rEventEpochEnd\x12\x14\n\x0c\x65poch_number\x18\x01 \x01(\x04\x42.Z,github.com/NibiruChain/nibiru/x/epochs/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epochs.event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/NibiruChain/nibiru/x/epochs/types'
  _EVENTEPOCHSTART.fields_by_name['epoch_start_time']._options = None
  _EVENTEPOCHSTART.fields_by_name['epoch_start_time']._serialized_options = b'\220\337\037\001\310\336\037\000'
  _EVENTEPOCHSTART._serialized_start=95
  _EVENTEPOCHSTART._serialized_end=198
  _EVENTEPOCHEND._serialized_start=200
  _EVENTEPOCHEND._serialized_end=237
# @@protoc_insertion_point(module_scope)
