"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import util.v1.query_pb2

class QueryStub:
    """Query defines the gRPC querier service."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    ModuleAccounts: grpc.UnaryUnaryMultiCallable[
        util.v1.query_pb2.QueryModuleAccountsRequest,
        util.v1.query_pb2.QueryModuleAccountsResponse,
    ]
    """Queries the reserve assets in a given pool, identified by a token pair."""

class QueryServicer(metaclass=abc.ABCMeta):
    """Query defines the gRPC querier service."""

    @abc.abstractmethod
    def ModuleAccounts(
        self,
        request: util.v1.query_pb2.QueryModuleAccountsRequest,
        context: grpc.ServicerContext,
    ) -> util.v1.query_pb2.QueryModuleAccountsResponse:
        """Queries the reserve assets in a given pool, identified by a token pair."""

def add_QueryServicer_to_server(servicer: QueryServicer, server: grpc.Server) -> None: ...
