"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import vpool.v1.state_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines the vpool module's genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VPOOLS_FIELD_NUMBER: builtins.int
    @property
    def vpools(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[vpool.v1.state_pb2.Vpool]: ...
    def __init__(
        self,
        *,
        vpools: collections.abc.Iterable[vpool.v1.state_pb2.Vpool] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["vpools", b"vpools"]) -> None: ...

global___GenesisState = GenesisState
